[package]
name = "hust-network-login"
version = "0.1.1"
authors = ["black-binary <blackbinary@qq.com>"]
edition = "2018"

[dependencies]
minreq = {version = "2.2", features = []}
urlencoding = "1.1"

[profile.release]
lto = "fat"
opt-level = 'z'
codegen-units = 1
panic = 'abort'